image: python:latest

stages:
  - prep
  - build
  - test
  - Static Analysis
  - deploy

before_script:
  - python --version
  #pip install -r requirements.txt

prep:
  stage: prep
  script:
    - pip install -r requirements.txt
  artifacts:
   paths:
   - python_packages
  cache:
   paths:
   - python_packages


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
build-start:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
  artifacts:
    paths:
      - public

test-django-backend:
  stage: test
  script:
    - cd django_api
    - python manage.py migrate
    - python manage.py test
  artifacts:
    paths:
      - public


flake8:
  stage: Static Analysis
  script:
    - flake8 --ignore=W293,W391 --exclude 'django_api/venv/*' --max-line-length=120 .
  artifacts:
    paths:
      - public

coverage:
  stage: Static Analysis
  script:
    #We should update this to run all tests. It is only running the py_edgar_lite tests
    - cd django_api
    - coverage run --omit 'venv/*' --source='.' manage.py test
    - coverage report
    - coverage erase
  artifacts:
    paths:
      - public

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  artifacts:
    paths:
      - public
