image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
build-start:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-django-backend:
  stage: test
  script:
    - pip install virtualenv
    - pip install coverage
    - cd Backend
    - virtualenv newenv
    - source newenv/bin/activate
    - pip install django
    - pip install djangorestframework
    - python manage.py migrate
    - coverage run --source='.' manage.py test
    - coverage report
    - coverage erase


test-job1:
  stage: test
  script:
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
