image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test
  - Static Analysis
  - deploy

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.


pages:
  stage: deploy
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs
    - sphinx-build -b html . public
  artifacts:
    paths:
      - public

#deploy-prod:
#  stage: deploy
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd docs
#    - make html
#    - cd ..
#    - cp -R docs/build/html/_static api_comms/flask_app/_static
#    - rm -d -r docs/build/html/_static
#    - rm -d -r docs/build/html/_sources
#    - mkdir -p api_comms/flask_app/templates/docs
#    - mkdir -p api_comms/flask_app/templates/docs/html
#    - cp -R docs/build/html api_comms/flask_app/templates/docs/html
#    - rm -d -r docs/build
