image: python:latest

stages:
  - build
  - test
  - Static Analysis
  - deploy

before_script:
  - python --version
  #pip install -r requirements.txt

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
build-start:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-django-backend:
  stage: test
  script:
    - cd django_api
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py test


flake8:
  stage: Static Analysis
  script:
    - pip install flake8
    - flake8 --ignore=W293,W391 --exclude 'django_api/venv/*' --max-line-length=120 .

coverage:
  stage: Static Analysis
  script:
    #We should update this to run all tests. It is only running the py_edgar_lite tests
    - pip install pytest
    - pip install coverage
    - coverage run -m pytest report_generator/test_report_generator
    - coverage run -m pytest django_api/report_schema/tests
    - cd django_api
    - virtualenv venv
    - source venv/bin/activate
    - pip install Django
    - pip install djangorestframework
    - pip install psycopg2-binary
    - coverage run --omit 'venv/*' --source='.' manage.py test
    - coverage report
    - coverage erase

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
