image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
build-start:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-django-backend:
  stage: test
  script:
    - pip install virtualenv
    - cd Backend
    - virtualenv venv
    - source venv/bin/activate
    - pip install coverage
    - pip install Django
    - pip install djangorestframework
    - pip install psycopg2-binary
    - python manage.py migrate
    - coverage run --omit 'venv/*' --source='.' manage.py test
    - coverage report
    - coverage erase

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
