image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.

build-start:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

build-django-backend:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pip install virtualenv
    - virtualenv newenv
    - source newenv/bin/activate
    - pip install django
    - pip install djangorestframework
    - python Backend/manage.py migrate
    - echo "Django backed setup complete!"

test-django-backend:
  stage: test
  script:
    - python Backend/manage.py test

test-job1:
  stage: test
  script:
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
