version: '3.9'

services:
    postgres-db:
        image: postgres:latest
        container_name: postgres-db
        volumes:
          - pgdata:/var/lib/postgresql/data
        env_file:
            - ./.env/postgres.env
        restart: always
        ports:
            - "5432:5432"
        networks:
            - main
    django-server:
        container_name: django-server
        build: ./django_api
        image: django-server:latest
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - django-data:/django_api
        env_file:
            - ./.env/django.env
        ports:
            - "8000:8000"
        depends_on:
            - postgres-db
        restart: always
        networks:
            - main
    flask-server:
        container_name: flask-server
        build: ./api_comms
        image: flask-server:latest
        command: python3 app.py
        volumes:
            - flask-data:/api_comms
        env_file:
            - ./.env/flask.env
        ports:
            - "5000:5000"
        depends_on:
            - postgres-db
            - django-server
        restart: always
        networks:
            - main

volumes:
    pgdata:
    django-data:
    flask-data:
    report-data:
    

networks:
    main:
